# Generated by Django 2.2.2 on 2019-07-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_address', models.CharField(max_length=50)),
                ('password', models.IntegerField()),
                ('identifying_code', models.CharField(max_length=10)),
            ],
        ),
    ]
